/**
 * Placeholder: future Claude API content generation.
 *
 * This script will NOT auto-publish. It writes draft JSON files to
 * content/suggestions/ for human review before moving to content/published/.
 *
 * Planned flow:
 * 1. Load content/sources/sources.json for research context
 * 2. Call Claude API with structured output prompt + Zod schema
 * 3. Write result to content/suggestions/{type}/{slug}.json
 * 4. Include metadata: generatedAt, sourceIds, model, status: "draft"
 */

import fs from "fs";
import path from "path";
import { SUGGESTIONS_ROOT } from "../src/content/paths";
import { useCaseSchema } from "../src/content/schemas";

const PLACEHOLDER_SLUG = "example-draft-use-case";

function main() {
  const type = process.argv[2] ?? "use-cases";
  const outDir = path.join(SUGGESTIONS_ROOT, type);
  fs.mkdirSync(outDir, { recursive: true });

  const draft = {
    _meta: {
      status: "draft",
      generatedAt: new Date().toISOString(),
      generator: "scripts/generate-suggestion.ts (placeholder)",
      model: "claude-sonnet (not connected)",
      sourceIds: ["src-openai-docs", "src-google-workspace-dev"],
      reviewRequired: true,
      notes:
        "Placeholder only. Future Claude API output will validate against Zod schemas before writing here.",
    },
    suggestion: {
      id: "uc-draft-001",
      slug: PLACEHOLDER_SLUG,
      title: "Example Draft Use Case (Do Not Publish)",
      category: "Operations",
      industries: ["Any SMB"],
      businessFunctions: ["Owner/Admin"],
      summary: "Placeholder draft generated by the suggestion pipeline.",
      businessProblem: "Replace with LLM-generated content after review.",
      outcome: "Replace with LLM-generated content after review.",
      whoItsFor: "Replace with LLM-generated content after review.",
      requiredDataSources: ["emails"],
      aiInputs: ["Example input"],
      aiOutputs: ["Example output"],
      requiredApis: ["gmail-api", "openai-api"],
      noCodeTools: ["Zapier"],
      lowCodeTools: ["n8n"],
      customBuildStack: ["Node.js"],
      implementationSteps: ["Step 1: Review this draft manually"],
      systemBehavior: ["Never auto-publish from suggestions/"],
      risks: ["Draft content is unreviewed"],
      difficulty: "Beginner",
      automationLevel: "Semi-automated",
      valuePotential: "Medium",
      relatedUseCases: [],
      tags: ["draft", "placeholder"],
      featured: false,
    },
  };

  const parsed = useCaseSchema.safeParse(draft.suggestion);
  if (!parsed.success) {
    console.error("Placeholder draft failed schema validation:", parsed.error.message);
    process.exit(1);
  }

  const outFile = path.join(outDir, `${PLACEHOLDER_SLUG}.json`);
  fs.writeFileSync(outFile, `${JSON.stringify(draft, null, 2)}\n`, "utf-8");

  console.log("Placeholder suggestion written (NOT published):");
  console.log(`  ${outFile}`);
  console.log("\nFuture Claude API integration will:");
  console.log("  - Read sources from content/sources/sources.json");
  console.log("  - Generate schema-valid JSON into content/suggestions/");
  console.log("  - Require human review before copying to content/published/");
}

main();
